### ISSUE TITLE
not working , doesn't compile

### ISSUE THREAD

**Issue by k2milad** [bhassani/EternalBlueC#1]
your repository is full of error!
python script 64bit.py and 32bit.py not runnning it says indent error and c sources doesn't compile it says PATH_MAX not find.
and eternalblue.c is very large string it doens't compile.
full of full error not working did you even test it????

**Comment by k2milad** [comment]
You just upload some bunch of .c and .py files that even doesn't compile

**Comment by bhassani** [comment]
Hello,

The Python scripts are not mine and were uploaded so I can convert it to C in the same way they implemented it.  Yes, there are indent errors, if you want you can fix the indentation errors.  It is not difficult to do.  However, I am porting it to C so I don't care about it functioning.

I cannot explain your PATH_MAX error but it appears to be maybe you are compiling it on Linux? and not Windows.

The EternalBlue code is not completed and is not functional yet.  As described on the README page and the in comments in the source code.
