### ISSUE TITLE
Undefined function 'extract_lib' in Eternal blue All in one source code

### ISSUE THREAD

**Issue by lyndoncoin** [bhassani/EternalBlueC#10]
Hi I've got the code compiling if I replace if(extract_lib(TEMP_EXTRACT_DIR) != 0) with if(1) etc,

I cant find the function extract_lib in any of the source code,

There is just a prototype definition in global.h,

Any direction here?

Thanks in advance

**Comment by lyndoncoin** [comment]
sorry global.h should of read dep_lib.h

**Comment by bhassani** [comment]
Eternalblue all in one source code is not supported by me; it's merely in here as learning material

Repository also contains the following for educational purposes and are NOT supported by me:
[*] EternalBlue All in one binary
