### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Brumairef** [bhassani/EternalBlueC#12]
In the folder ". \ eternalblue all in one \ enc_res", are two files "res_decode. C" and "dep_lib. C" missing.

I think the others correspond to a ". H" and a ". C" file.

Then I also debugged and reported an error.

Error display get_ decode_ Hex is an external symbol.

That is "enc_res_desc get_decode_hex (char * pb64buf);" something the matter.

There seems to be no "res_decode. C".

Please take the time to revise it. If you can, please contact me.

My email address is: **easonmook@163.com**

**Comment by bhassani** [comment]
Hello,

I have stated that this is not supported by me.  This is included as a collection item under "Extra code".  That is not my project, nor supported by me.  Please refer to the README document:

Repository also contains the following for educational purposes and are NOT supported by me:

**[*] EternalBlue All in one binary**
