### ISSUE TITLE
Can anyone tell me how to generate the eternalblue.dat file from pcap

### ISSUE THREAD

**Issue by ZeroXLN** [bhassani/EternalBlueC#14]

**Comment by ZeroXLN** [comment]
@bhassani 
Can anyone tell me how to generate the eternalblue.dat file from pcap?
I want to know, how to generate the replay file from pcap? like this
![image](https://user-images.githubusercontent.com/58169480/216890047-513bc7e8-3418-4ab1-bb71-543b15275964.png)

**Comment by bhassani** [comment]
Just so that you are aware, I don't support that script, I just put it here for reference.  

If you want to use the eternalblue.dat file run the eternalblue.py script in the same folder.
