### ISSUE TITLE
Various compilation Errors

### ISSUE THREAD

**Issue by manuelinfosec** [bhassani/EternalBlueC#2]
I think it's better if you could add the compiled binaries to your repository other than putting us through the stress of compiling and debugging your code...

**Comment by bhassani** [comment]
I will add the compiled binaries when I get the chance.  I didn't feel Github users would trust if I post compiled binaries out of security fears.  

Can you provide which names of the source code you are experiencing problems with?  I can patch them up quickly.

The code not found in the main directory are not supported by me and are merely source code I want archived as they relate to this project.

**Comment by bhassani** [comment]
No response from individual.

Closing this issue.

**Comment by manuelinfosec** [comment]
Can you mail me the binaries compressed? 

njokuchiemezie01@gmail.com

**Comment by manuelinfosec** [comment]
> No response from individual.
> 
> Closing this issue.

Very sorry.
