### ISSUE TITLE
Compile Errors 100+

### ISSUE THREAD

**Issue by malcrypsi** [bhassani/EternalBlueC#6]
Undeclared identifiers in EternalBlueC-master\EternalBluecpp.cpp
smbnegociate
session_setup
treeconnect
NTTrans
NTTrans2
NTTrans3
.
..
..
NTTrans46
SmbEcho
negociate2
unknown_packet_socket2
unknown_packet_socket3
.
..
...
unknown_packet_socket21
negociate_socket16
smbecho_socket1
last_eternalblue_packet
last_eternalblue_packet2
last_eternalblue_packet3
doublepulsar_packet_socket3
doublepulsar_packet_socket4
.
..
...
doublepulsar_packet_socket21
doublepulsar_pkt
disconnect
logoff

These are about 100+ compile errors, I was able to find some of these from other cpp but most variables are just not defined. Can you please check
![image](https://user-images.githubusercontent.com/75301157/100713723-8ad27b80-33d6-11eb-8c59-ab58aca84c59.png)

**Comment by loneicewolf** [comment]
@malcrypsi  I am not involved in this project,  But I will try on my side tomorrow. And I'll come back with the results.
As this seems quite fascinating I must admit!

Regards
